import io from "socket.io-client";
import {useEffect, useState} from "react";


export default function Chat(){
    const [socket,setSocket] = useState(null);

    useEffect(()=>{
        const newSocket = io();
        setSocket(newSocket);


        newSocket.on("connect",()=>{
            console.log("user connected");
        })
        newSocket.on("disconnect",()=>{
            console.log("user disconnected");
        })
        //handle errors generated by a refused connection
        newSocket.on("connect_error", (err) => {
            if (err.data){
                //show an error if there is something wrong with the cookie credentials
                console.error(err.message + ": " + err.data.details);
            }else{
                console.error(err.message);
            }
        });

        return ()=>{
            newSocket.off("connect");
            newSocket.off("disconnect");
            newSocket.close();
        }

    }, [setSocket]);

    return (
        <div>
            chat here
        </div>
    )
}